type Mutation {
    addPermission(
        staffId: Int!
        permissionModule: String!
        value: String!
    ): MutationResponse!

    deletePermission(
        staffId: Int!
        permissionModule: String!
        value: String!
    ): MutationResponse!
}