type Mutation {
    addTransport(
        branchId: Int!
        model: String!
        color: String!
        img: Upload!
    ): MutationResponse!
    
    changeTransport(
        transportId: Int!
        model: String!
        color: String!
    ): MutationResponse!
    
    deleteTransport(
        transportId: Int!
    ): MutationResponse!
}


type Transport {
    transportId: Int
    branchId: Int
    model: String
    color: String
    img: String
    transportAddedAt: String
}