type Mutation {
    addBranch(
        branchname: String!
        address: String!
    ): MutationResponse!
    
    changeBranch(
        branchId: Int!
        branchname: String!
        address: String!
    ): MutationResponse!
    
    deleteBranch(
        branchId: Int!
    ): MutationResponse!
}

type Branch {
    branchid: ID
    branchname: String
    addedTime: String
    address: String
}